"""The warehouse catalog, rendered from dbt's manifest and the lake.

Descriptions come from `schema.yml`, types and column order from the lake. The page under
`docs/` is output: regenerate it with `make catalog` rather than editing it.
"""

from __future__ import annotations

import json
import re
from typing import Any

import duckdb

from config import settings
from connectors import ducklake
from utils.exceptions import ToolingError

MANIFEST = settings.DBT_DIR / "target" / "manifest.json"

# Layer by layer, outermost first: a reader looking for a column starts at the published surface.
LAYERS = [
    ("marts", "Published surface", "One row per sales order line, every dimension flattened on."),
    ("core", "Star schema", "Conformed dimensions and the fact they hang off."),
]


def _manifest() -> dict[str, Any]:
    if not MANIFEST.exists():
        raise ToolingError(f"{MANIFEST} is missing -- run `make parse` first")
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def _by_relation(manifest: dict[str, Any]) -> dict[tuple[str, str], dict[str, Any]]:
    """Models keyed the way the lake names them, so the two halves can be joined."""
    return {
        (node["schema"], node["alias"] or node["name"]): node
        for node in manifest["nodes"].values()
        if node["resource_type"] == "model"
    }


def _tests_by_column(manifest: dict[str, Any]) -> dict[tuple[str, str], dict[str, list[str]]]:
    """Which tests guard each column, keyed the way the lake names a relation."""
    nodes = manifest["nodes"]
    found: dict[tuple[str, str], dict[str, list[str]]] = {}
    for node in nodes.values():
        meta = node.get("test_metadata")
        if node["resource_type"] != "test" or not meta:
            continue
        model = nodes.get(node.get("attached_node") or "")
        column = meta["kwargs"].get("column_name")
        if model is None or column is None:
            continue
        name = meta["name"]
        if name == "relationships":
            # `to` arrives as the literal Jinja, e.g. "ref('dim_date')".
            referenced = re.search(r"'([^']+)'", str(meta["kwargs"].get("to", "")))
            field = meta["kwargs"].get("field")
            name = f"-> {referenced.group(1)}.{field}" if referenced else "relationships"
        relation = (model["schema"], model["alias"] or model["name"])
        found.setdefault(relation, {}).setdefault(column, []).append(name)
    return found


def report(conn: duckdb.DuckDBPyConnection) -> str:
    manifest = _manifest()
    models = _by_relation(manifest)
    tests = _tests_by_column(manifest)

    lines = [
        "# Data warehouse catalog",
        "",
        "> Generated by `make catalog`. Do not edit: the descriptions come from the dbt",
        "> `schema.yml` files, the types and the column order from the lake. Row counts are",
        "> deliberately absent -- `make shape` prints those, and they go stale in a document.",
    ]

    for schema, title, blurb in LAYERS:
        relations = [name for found, name, _ in ducklake.relations(conn) if found == schema]
        if not relations:
            raise ToolingError(f"{ducklake.CATALOG}.{schema} holds nothing -- run `make build`")
        lines += ["", f"## {title} (`{schema}`)", "", blurb]

        for relation in sorted(relations):
            node = models.get((schema, relation))
            columns = conn.execute(
                "select column_name, data_type from information_schema.columns "
                f"where table_catalog = '{ducklake.CATALOG}' and table_schema = '{schema}' "
                f"and table_name = '{relation}' order by ordinal_position"
            ).fetchall()
            guards = tests.get((schema, relation), {})

            lines += ["", f"### `{relation}`", ""]
            if node and node.get("description"):
                lines += [" ".join(node["description"].split()), ""]
            lines += ["| Column | Type | Tests | Description |", "|---|---|---|---|"]
            described = (node or {}).get("columns", {})
            for column, data_type in columns:
                note = " ".join(described.get(column, {}).get("description", "").split())
                guard = ", ".join(f"`{g}`" for g in sorted(guards.get(column, [])))
                lines.append(f"| `{column}` | {data_type.lower()} | {guard} | {note} |")

    return "\n".join(lines) + "\n"
