"""The raw schema without its rows: what lets every model build where the source cannot be reached.

`ddl()` reads the column types of the tables dbt reads from the real lake, and `make raw_schema`
commits the result. `create()` builds a local DuckLake from that file -- a DuckDB-file catalog and
a directory of Parquet, the same table format as the real lake with nothing to connect to. The
dbt target `empty` attaches it, and `make build_empty` runs `dbt build --empty` against it.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import duckdb

from config import settings
from connectors import ducklake
from ingestion import tables as tables_contract
from utils import sql
from utils.exceptions import ToolingError

# The one dlt table a model reads: the load gate and the dlt source name it.
DLT_TABLES = ("_dlt_loads",)

HEADER = """\
-- The lake's raw schema as types, without rows. Generated by `make raw_schema` from a loaded lake;
-- do not edit. `make build_empty` builds every model on top of it, which is how CI runs SQL
-- without the source. Regenerate after a change to src/ingestion/tables.yml or to dlt.
"""


def expected_tables() -> list[str]:
    """Every raw table a model reads: the extraction contract, plus dlt's load record."""
    return sorted([entry["output"] for entry in tables_contract.load()["tables"]] + [*DLT_TABLES])


def ddl(conn: duckdb.DuckDBPyConnection) -> str:
    """`create table` statements for the raw tables dbt reads, with the lake's own types."""
    schema = settings.RAW_SCHEMA
    wanted = expected_tables()
    rows = conn.execute(
        "select table_name, column_name, data_type, is_nullable "
        "from information_schema.columns "
        f"where table_catalog = '{ducklake.CATALOG}' and table_schema = ? "
        "order by table_name, ordinal_position",
        [schema],
    ).fetchall()
    columns: dict[str, list[str]] = {}
    for table, column, data_type, nullable in rows:
        if table in wanted:
            not_null = "" if nullable == "YES" else " not null"
            columns.setdefault(table, []).append(f'    "{column}" {data_type}{not_null}')

    missing = [table for table in wanted if table not in columns]
    if missing:
        raise ToolingError(
            f"{ducklake.CATALOG}.{schema} does not hold {', '.join(missing)} -- run `make extract`"
        )
    statements = [f"create schema if not exists {schema};"]
    statements += [
        f'create table {schema}."{table}" (\n' + ",\n".join(columns[table]) + "\n);"
        for table in wanted
    ]
    return HEADER + "\n" + "\n\n".join(statements)


def create(directory: Path = settings.EMPTY_LAKE_DIR, schema_ddl: Path | None = None) -> str:
    """A fresh local DuckLake holding the raw schema and nothing else.

    Recreated on every call: a lake left by the previous run would hold the models it built, and
    `dbt build` must start from raw alone, as it does on the real lake.
    """
    source = schema_ddl or settings.RAW_SCHEMA_DDL
    if not source.exists():
        raise ToolingError(f"{source} is missing -- run `make raw_schema` with the lake loaded")
    shutil.rmtree(directory, ignore_errors=True)
    (directory / "data").mkdir(parents=True)

    conn = duckdb.connect()
    conn.execute("install ducklake")
    conn.execute("load ducklake")
    conn.execute(
        f"attach {sql.literal('ducklake:' + str(directory / 'metadata.ducklake'))} "
        f"as {ducklake.CATALOG} (data_path {sql.literal(str(directory / 'data') + '/')})"
    )
    conn.execute(f"use {ducklake.CATALOG}")
    try:
        conn.execute(source.read_text(encoding="utf-8"))
    except duckdb.Error as error:
        raise ToolingError(f"{source} does not build: {error}") from error
    count = conn.execute(
        "select count(*) from information_schema.tables "
        f"where table_catalog = '{ducklake.CATALOG}' and table_schema = ?",
        [settings.RAW_SCHEMA],
    ).fetchone()
    conn.close()
    return f"empty lake at {directory}: {count[0] if count else 0} raw tables, no rows"
