-- The lake's raw schema as types, without rows. Generated by `make raw_schema` from a loaded lake;
-- do not edit. `make build_empty` builds every model on top of it, which is how CI runs SQL
-- without the source. Regenerate after a change to src/ingestion/tables.yml or to dlt.

create schema if not exists raw;

create table raw."_dlt_loads" (
    "load_id" VARCHAR not null,
    "schema_name" VARCHAR,
    "status" BIGINT not null,
    "inserted_at" TIMESTAMP WITH TIME ZONE not null,
    "schema_version_hash" VARCHAR
);

create table raw."application__cities" (
    "city_id" BIGINT not null,
    "city_name" VARCHAR not null,
    "state_province_id" BIGINT not null,
    "latest_recorded_population" BIGINT,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."application__countries" (
    "country_id" BIGINT not null,
    "country_name" VARCHAR not null,
    "formal_name" VARCHAR not null,
    "iso_alpha3_code" VARCHAR,
    "iso_numeric_code" BIGINT,
    "country_type" VARCHAR,
    "latest_recorded_population" BIGINT,
    "continent" VARCHAR not null,
    "region" VARCHAR not null,
    "subregion" VARCHAR not null,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."application__delivery_methods" (
    "delivery_method_id" BIGINT not null,
    "delivery_method_name" VARCHAR not null,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."application__people" (
    "person_id" BIGINT not null,
    "full_name" VARCHAR not null,
    "preferred_name" VARCHAR not null,
    "search_name" VARCHAR not null,
    "is_permitted_to_logon" BOOLEAN not null,
    "logon_name" VARCHAR,
    "is_external_logon_provider" BOOLEAN not null,
    "is_system_user" BOOLEAN not null,
    "is_employee" BOOLEAN not null,
    "is_salesperson" BOOLEAN not null,
    "user_preferences" VARCHAR,
    "phone_number" VARCHAR,
    "fax_number" VARCHAR,
    "email_address" VARCHAR,
    "custom_fields" VARCHAR,
    "other_languages" VARCHAR,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."application__state_provinces" (
    "state_province_id" BIGINT not null,
    "state_province_code" VARCHAR not null,
    "state_province_name" VARCHAR not null,
    "country_id" BIGINT not null,
    "sales_territory" VARCHAR not null,
    "latest_recorded_population" BIGINT,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."purchasing__supplier_categories" (
    "supplier_category_id" BIGINT not null,
    "supplier_category_name" VARCHAR not null,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."purchasing__suppliers" (
    "supplier_id" BIGINT not null,
    "supplier_name" VARCHAR not null,
    "supplier_category_id" BIGINT not null,
    "primary_contact_person_id" BIGINT not null,
    "alternate_contact_person_id" BIGINT not null,
    "delivery_method_id" BIGINT,
    "delivery_city_id" BIGINT not null,
    "postal_city_id" BIGINT not null,
    "supplier_reference" VARCHAR,
    "bank_account_name" VARCHAR,
    "bank_account_branch" VARCHAR,
    "bank_account_code" VARCHAR,
    "bank_account_number" VARCHAR,
    "bank_international_code" VARCHAR,
    "payment_days" BIGINT not null,
    "internal_comments" VARCHAR,
    "phone_number" VARCHAR not null,
    "fax_number" VARCHAR not null,
    "website_url" VARCHAR not null,
    "delivery_address_line1" VARCHAR not null,
    "delivery_address_line2" VARCHAR,
    "delivery_postal_code" VARCHAR not null,
    "postal_address_line1" VARCHAR not null,
    "postal_address_line2" VARCHAR,
    "postal_postal_code" VARCHAR not null,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."sales__buying_groups" (
    "buying_group_id" BIGINT not null,
    "buying_group_name" VARCHAR not null,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."sales__customer_categories" (
    "customer_category_id" BIGINT not null,
    "customer_category_name" VARCHAR not null,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."sales__customers" (
    "customer_id" BIGINT not null,
    "customer_name" VARCHAR not null,
    "bill_to_customer_id" BIGINT not null,
    "customer_category_id" BIGINT not null,
    "buying_group_id" BIGINT,
    "primary_contact_person_id" BIGINT not null,
    "alternate_contact_person_id" BIGINT,
    "delivery_method_id" BIGINT not null,
    "delivery_city_id" BIGINT not null,
    "postal_city_id" BIGINT not null,
    "credit_limit" DECIMAL(18,2),
    "account_opened_date" DATE not null,
    "standard_discount_percentage" DECIMAL(18,3) not null,
    "is_statement_sent" BOOLEAN not null,
    "is_on_credit_hold" BOOLEAN not null,
    "payment_days" BIGINT not null,
    "phone_number" VARCHAR not null,
    "fax_number" VARCHAR not null,
    "delivery_run" VARCHAR,
    "run_position" VARCHAR,
    "website_url" VARCHAR not null,
    "delivery_address_line1" VARCHAR not null,
    "delivery_address_line2" VARCHAR,
    "delivery_postal_code" VARCHAR not null,
    "postal_address_line1" VARCHAR not null,
    "postal_address_line2" VARCHAR,
    "postal_postal_code" VARCHAR not null,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."sales__order_lines" (
    "order_line_id" BIGINT not null,
    "order_id" BIGINT not null,
    "stock_item_id" BIGINT not null,
    "description" VARCHAR not null,
    "package_type_id" BIGINT not null,
    "quantity" BIGINT not null,
    "unit_price" DECIMAL(18,2),
    "tax_rate" DECIMAL(18,3) not null,
    "picked_quantity" BIGINT not null,
    "picking_completed_when" TIMESTAMP,
    "last_edited_by" BIGINT not null,
    "last_edited_when" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."sales__orders" (
    "order_id" BIGINT not null,
    "customer_id" BIGINT not null,
    "salesperson_person_id" BIGINT not null,
    "picked_by_person_id" BIGINT,
    "contact_person_id" BIGINT not null,
    "backorder_order_id" BIGINT,
    "order_date" DATE not null,
    "expected_delivery_date" DATE not null,
    "customer_purchase_order_number" VARCHAR,
    "is_undersupply_backordered" BOOLEAN not null,
    "comments" VARCHAR,
    "delivery_instructions" VARCHAR,
    "internal_comments" VARCHAR,
    "picking_completed_when" TIMESTAMP,
    "last_edited_by" BIGINT not null,
    "last_edited_when" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."warehouse__colors" (
    "color_id" BIGINT not null,
    "color_name" VARCHAR not null,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."warehouse__package_types" (
    "package_type_id" BIGINT not null,
    "package_type_name" VARCHAR not null,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);

create table raw."warehouse__stock_items" (
    "stock_item_id" BIGINT not null,
    "stock_item_name" VARCHAR not null,
    "supplier_id" BIGINT not null,
    "color_id" BIGINT,
    "unit_package_id" BIGINT not null,
    "outer_package_id" BIGINT not null,
    "brand" VARCHAR,
    "size" VARCHAR,
    "lead_time_days" BIGINT not null,
    "quantity_per_outer" BIGINT not null,
    "is_chiller_stock" BOOLEAN not null,
    "barcode" VARCHAR,
    "tax_rate" DECIMAL(18,3) not null,
    "unit_price" DECIMAL(18,2) not null,
    "recommended_retail_price" DECIMAL(18,2),
    "typical_weight_per_unit" DECIMAL(18,3) not null,
    "marketing_comments" VARCHAR,
    "internal_comments" VARCHAR,
    "custom_fields" VARCHAR,
    "tags" VARCHAR,
    "search_details" VARCHAR not null,
    "last_edited_by" BIGINT not null,
    "valid_from" TIMESTAMP not null,
    "valid_to" TIMESTAMP not null,
    "_dlt_load_id" VARCHAR not null
);
